#!/usr/bin/env python3
"""
generate_seed.py
Generates scripts/db/002_seed.sql from the two CSV source files.
Run from the project root or scripts/db directory.
"""

import csv
import os
import re

# Resolve paths relative to this script's location
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data")
OUT_FILE = os.path.join(SCRIPT_DIR, "002_seed.sql")
HASHES_FILE = os.path.join(SCRIPT_DIR, "hashes.txt")

ING_CSV = os.path.join(DATA_DIR, "Ingredientes y Materiales - Ingredientes.csv")
MAT_CSV = os.path.join(DATA_DIR, "Ingredientes y Materiales - Materiales.csv")


def load_hashes() -> dict:
    """Read bcryptjs hashes from hashes.txt (generated by gen-hashes.js)."""
    result = {}
    with open(HASHES_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if ":" not in line:
                continue
            key, _, val = line.partition(":")
            result[key.strip()] = val.strip()
    required = {"SUPERADMIN", "ADMIN", "USER"}
    missing = required - result.keys()
    if missing:
        raise RuntimeError(
            f"hashes.txt is missing entries: {missing}. Run gen-hashes.js first."
        )
    return result


def parse_price(raw: str) -> str:
    """Convert a Spanish-locale price string to a SQL numeric literal."""
    raw = raw.strip().strip('"').replace(",", ".").strip()
    if not raw:
        return "0.00"
    try:
        float(raw)
        return raw
    except ValueError:
        return "0.00"


def escape_sql(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")


def read_csv(path: str, name_col: str, unit_col: str, price_col: str):
    """Read a CSV and return a list of (name, unit, price_str) tuples, skipping the header."""
    rows = []
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row.get(name_col, "").strip()
            unit = row.get(unit_col, "").strip()
            price = parse_price(row.get(price_col, "0"))
            if name:
                rows.append((name, unit, price))
    return rows


def build_sql():
    hashes = load_hashes()
    ingredients = read_csv(ING_CSV, "INGREDIENTES", "MEDIDA", "PRECIO")
    materials = read_csv(MAT_CSV, "MATERIAL", "MEDIDA", "PRECIO")

    lines = []

    lines.append("-- ============================================================")
    lines.append("-- 002_seed.sql  –  Seed inicial del Proyecto Lovelace")
    lines.append("-- Generado automáticamente por generate_seed.py")
    lines.append("-- Basado en estructura_lovelace.sql (schema real)")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    # ------------------------------------------------------------------
    # EXTENSION (idempotent)
    # ------------------------------------------------------------------
    lines.append("-- Extension uuid-ossp (por si no existe aún)")
    lines.append('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    lines.append("")
    lines.append("-- Extension pgcrypto (para bcrypt en passwords)")
    lines.append('CREATE EXTENSION IF NOT EXISTS pgcrypto;')
    lines.append("")

    # ------------------------------------------------------------------
    # USERS
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- USUARIOS")
    lines.append("-- Credenciales de desarrollo:")
    lines.append("--   admin@lovelace.edu        → SuperAdmin2026!")
    lines.append("--   carlos.ruiz@lovelace.edu  → Admin2026!")
    lines.append("--   maria.garcia@lovelace.edu → Usuario2026!")
    lines.append("-- ============================================================")
    lines.append("INSERT INTO public.users (id, email, password_hash, role, nombre, apellido1, apellido2, is_active)")
    lines.append("VALUES")
    lines.append("  (")
    lines.append("    '11111111-1111-1111-1111-111111111111',")
    lines.append("    'admin@lovelace.edu',")
    lines.append(f"    '{hashes['SUPERADMIN']}',")
    lines.append("    'SUPERADMIN',")
    lines.append("    'Ana',")
    lines.append("    'Martínez',")
    lines.append("    'López',")
    lines.append("    true")
    lines.append("  ),")
    lines.append("  (")
    lines.append("    '22222222-2222-2222-2222-222222222222',")
    lines.append("    'carlos.ruiz@lovelace.edu',")
    lines.append(f"    '{hashes['ADMIN']}',")
    lines.append("    'ADMIN',")
    lines.append("    'Carlos',")
    lines.append("    'Ruiz',")
    lines.append("    'Fernández',")
    lines.append("    true")
    lines.append("  ),")
    lines.append("  (")
    lines.append("    '33333333-3333-3333-3333-333333333333',")
    lines.append("    'maria.garcia@lovelace.edu',")
    lines.append(f"    '{hashes['USER']}',")
    lines.append("    'USER',")
    lines.append("    'María',")
    lines.append("    'García',")
    lines.append("    'Sánchez',")
    lines.append("    true")
    lines.append("  )")
    lines.append("ON CONFLICT (email) DO NOTHING;")
    lines.append("")

    # ------------------------------------------------------------------
    # SUPPLIERS
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- PROVEEDORES")
    lines.append("-- ============================================================")
    lines.append("INSERT INTO public.suppliers (id, name, is_active)")
    lines.append("VALUES")
    lines.append("  ('aaaaaaaa-0000-0000-0000-000000000001', 'Proveedor General', true)")
    lines.append("ON CONFLICT (name) DO NOTHING;")
    lines.append("")

    # ------------------------------------------------------------------
    # CATEGORIES  (name + product_type must be unique together)
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- CATEGORÍAS")
    lines.append("-- ============================================================")
    lines.append("INSERT INTO public.categories (id, name, product_type)")
    lines.append("VALUES")
    lines.append("  ('bbbbbbbb-0000-0000-0000-000000000001', 'Ingredientes', 'INGREDIENT'),")
    lines.append("  ('bbbbbbbb-0000-0000-0000-000000000002', 'Materiales',   'MATERIAL')")
    lines.append("ON CONFLICT (name, product_type) DO NOTHING;")
    lines.append("")

    # ------------------------------------------------------------------
    # PRODUCTS – INGREDIENTS
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- PRODUCTOS – INGREDIENTES  (%d filas)" % len(ingredients))
    lines.append("-- ============================================================")
    lines.append("INSERT INTO public.products")
    lines.append("  (code, name, product_type, unit_type, unit_price, supplier_id, category_id, created_by)")
    lines.append("VALUES")

    ing_rows = []
    for idx, (name, unit, price) in enumerate(ingredients, start=1):
        code = "ING-%04d" % idx
        safe_name = escape_sql(name)
        safe_unit = escape_sql(unit) if unit else "UNIDAD"
        row = (
            "  ('%s', '%s', 'INGREDIENT', '%s', %s,\n"
            "   (SELECT id FROM public.suppliers WHERE name = 'Proveedor General'),\n"
            "   (SELECT id FROM public.categories WHERE name = 'Ingredientes' AND product_type = 'INGREDIENT'),\n"
            "   '11111111-1111-1111-1111-111111111111')"
        ) % (code, safe_name, safe_unit, price)
        ing_rows.append(row)

    lines.append(",\n".join(ing_rows))
    lines.append("ON CONFLICT (code) DO NOTHING;")
    lines.append("")

    # ------------------------------------------------------------------
    # PRODUCTS – MATERIALS
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- PRODUCTOS – MATERIALES  (%d filas)" % len(materials))
    lines.append("-- ============================================================")
    lines.append("INSERT INTO public.products")
    lines.append("  (code, name, product_type, unit_type, unit_price, supplier_id, category_id, created_by)")
    lines.append("VALUES")

    mat_rows = []
    for idx, (name, unit, price) in enumerate(materials, start=1):
        code = "MAT-%04d" % idx
        safe_name = escape_sql(name)
        safe_unit = escape_sql(unit) if unit else "UNIDAD"
        row = (
            "  ('%s', '%s', 'MATERIAL', '%s', %s,\n"
            "   (SELECT id FROM public.suppliers WHERE name = 'Proveedor General'),\n"
            "   (SELECT id FROM public.categories WHERE name = 'Materiales' AND product_type = 'MATERIAL'),\n"
            "   '11111111-1111-1111-1111-111111111111')"
        ) % (code, safe_name, safe_unit, price)
        mat_rows.append(row)

    lines.append(",\n".join(mat_rows))
    lines.append("ON CONFLICT (code) DO NOTHING;")
    lines.append("")

    # ------------------------------------------------------------------
    # INVENTORY – initial rows for every product
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- INVENTARIO INICIAL")
    lines.append("-- Una fila en public.inventory por cada producto insertado")
    lines.append("-- ============================================================")
    lines.append("INSERT INTO public.inventory (product_id, current_qty)")
    lines.append("SELECT id, 0 FROM public.products")
    lines.append("ON CONFLICT (product_id) DO NOTHING;")
    lines.append("")

    lines.append("COMMIT;")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    sql = build_sql()
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"✅  Seed generado en: {OUT_FILE}")
    print(f"    Líneas escritas: {sql.count(chr(10))}")
